[WIP] Documentation for the gRPC module
loadimpact/k6-docs pull request #110
Opened 2020-09-17 11:02 UTC by rogchap

docs for: https://github.com/loadimpact/k6/pull/1623

2020-10-01 23:18 UTC, amossc requested changes

2020-10-01 23:18 UTC, amossc commented on src/data/markdown/docs/02 javascript api/09 k6-grpc/20 Client/10-Client-load-importpaths-protoFiles.md
> +| `MethodInfo.fullMethod` | string | The full RPC method string, i.e., `package.service/method`. |
`s/i.e./e.g./`

ref: https://www.grammarly.com/blog/know-your-latin-i-e-vs-e-g/

2020-10-01 23:18 UTC, amossc commented on src/data/markdown/docs/02 javascript api/09 k6-grpc.md
> +| `StatusOK` | OK is returned on success. |
Do you have to repeat the name of the status on the second column? It looks redundant.

2020-10-01 23:18 UTC, amossc commented on src/data/markdown/docs/02 javascript api/09 k6-grpc/20 Client/30-Client-invokerpc-url-request-params.md
> +The given method to invoke must have it's RPC schema previously loaded via the [Client.load()](/javascript-api/k6-grpc/client/client-load-importpaths----protofiles) function, otherwise an
`s/it's/its/`

2020-10-01 23:18 UTC, amossc commented on src/data/markdown/docs/02 javascript api/09 k6-grpc/20-Client.md
> +| [Client.connect(address [,params])](/javascript-api/k6-grpc/client/client-connect-address-params) | Open's a connection to the given gRPC server. |
`s/Open's/Opens/`

2020-10-01 23:18 UTC, amossc commented on src/data/markdown/docs/02 javascript api/09 k6-grpc/20-Client.md
> +| [Client.invokeRPC(url, request [,params])](/javascript-api/k6-grpc/client/client-invokerpc-url-request-params) | Makes a unary RPC for the given service/method and returns a [Response](/javascript-
`an unary`: https://www.a-or-an.com/a_an/unary

2020-11-16 12:14 UTC, simskij commented
This was added in #144. Closing without merging

2020-11-16 12:14 UTC, closed without merging