[chore] deploy a version of docs when PR is created
loadimpact/k6-docs pull request #114
Opened 2020-09-23 11:49 UTC by allansson

2020-09-25 14:36 UTC, simskij requested changes
All in all, the code looks good! However, the link posted is dead. We should likely tend to that before merging 😅

2020-10-06 10:17 UTC, allansson commented
> All in all, the code looks good! However, the link posted is dead. We should likely tend to that before merging 😅

So it turns out that I can't pin gatsby-plugin-s3 to the commit with the necessary "retainObjectsPattern"-feature because they build the plugin on pre-publish. We'll have to wait for the next release of the plugin before merging this PR. Will keep an eye on the package, and fix it whenever they decide to release.

2020-10-30 09:37 UTC, allansson commented
@simskij PR:s are now deployed to https://mdr-ci.staging.k6.io/docs. Try out the link above and you should see the deployed version. I think all the links are working as expected, but I might have missed some. External links to e.g. the app or the k6 homepage should go to the staging versions.

Now I don't want to play devops for a year or two. 😅

2020-10-30 14:16 UTC, simskij approved these changes

2020-10-30 14:17 UTC, merged