Cloudwatch result visualization
loadimpact/k6-docs pull request #119
Opened 2020-09-25 13:49 UTC by mostafa

2020-09-25 14:09 UTC, ppcano requested changes

2020-09-25 14:09 UTC, ppcano commented on src/data/markdown/docs/01 guides/03 Results visualization/09 Amazon CloudWatch.md
> +
IMO, this is unnecessary.

2020-09-25 14:09 UTC, ppcano commented on src/data/markdown/docs/01 guides/03 Results visualization/09 Amazon CloudWatch.md
> +- [Amazon CloudWatch](https://aws.amazon.com/cloudwatch/), a monitoring and observability solution.
I wouldn't add prerequisites to follow the same format than the other guides.

2020-09-25 14:09 UTC, ppcano commented on src/data/markdown/docs/01 guides/03 Results visualization/09 Amazon CloudWatch.md
> +
On the other guides, we don't give instructions to install k6.

It's assumed that you are running k6 in your local machine. Which it makes my next question, why do I need to install k6 in EC2?

I think the installation should go into the details with EC2.

1 - Start with install the CloudWatch agent. (See the instructions)
2 - configure the CloudWatch agent like ...
3 - Start the agent (
4 - Run the test and output the result to the agent.


This is the structure of the instructions for ->  
-> https://k6.io/docs/results-visualization/new-relic
- > https://k6.io/docs/results-visualization/datadog

2020-09-28 10:27 UTC, mostafa commented on src/data/markdown/docs/01 guides/01 Getting started/04 Results Output.md
> +| [New Relic](/results-visualization/new-relic)         | `k6 run --out statsd` |
Addressed.

2020-09-28 11:19 UTC, merged