[WIP] - Test authoring tools
loadimpact/k6-docs pull request #153
Opened 2020-11-13 17:11 UTC by ppcano

Communicate the Test Builder and Browser Recorder as tools available for the k6 OSS community.

2020-11-20 15:17 UTC, simskij requested changes
Great changes! Some nitpicks

2020-11-20 15:17 UTC, simskij commented on src/data/markdown/docs/01 guides/03 Test authoring/02 Recording a session/01 Browser recorder.md
> +- You may have no ability to impact the performance of the third-party service
```suggestion
- You may not have the ability to impact the performance of third-party services
```

2020-11-20 15:17 UTC, simskij commented on src/data/markdown/docs/01 guides/03 Test authoring/02 Recording a session/02 Har converter.md
> +> HAR is a file format used by all the browsers and various tools to export the recorded HTTP requests.
```suggestion
> HAR is a file format used by all major browsers and various other tools to export recorded HTTP requests.
```

2020-11-20 15:17 UTC, simskij commented on src/data/markdown/docs/03 cloud/01 Creating and running a test/01 Test authoring.md
> +k6 is, at its core, a **Code-based testing tool**. Besides, the k6 ecosystem provides a set of **Codeless tools** to speed up the test creation and facilitate collaboration across different roles.
```suggestion
k6 is, at its core, a **Code-based testing tool**. However, the k6 ecosystem provides a set of **codeless tools** to speed up the test creation and facilitate collaboration across different roles.
```

2020-11-20 15:17 UTC, simskij commented on .vale/Vocab/docs/accept.txt
> +Codeless
```suggestion
Codeless
```
```suggestion
(?i)codeless
```

2020-11-20 15:17 UTC, simskij commented on src/data/markdown/docs/03 cloud/01 Creating and running a test/01 Test authoring.md
> +After creating your test, you might want to debug it locally or run it on the cloud. The cloud test will be launched from the geographic location/s - selected in your test - on the k6 Cloud infrastru
```suggestion
After creating your test, you might want to debug it locally or run it on the cloud. Cloud tests will be executed from the geographic location/s you've selected in your test, on k6 Cloud infrastructure. 
```

2020-11-20 15:17 UTC, simskij commented on src/data/markdown/docs/03 cloud/01 Creating and running a test/03 script editor.md
> +The script editor is designed to allow you to quickly write and mock up test scripts right within the web app.
```suggestion
The script editor is designed to allow you to quickly write test scripts from within the web app. 
```

2020-11-20 15:17 UTC, simskij commented on src/data/markdown/docs/03 cloud/01 Creating and running a test/03 script editor.md
> +We believe most users will quickly graduate to using k6 as a CLI and their IDE of choice locally. However, organizational security rules vary from organization to organization and some may not be abl
```suggestion
We believe most users will quickly graduate to using k6 as a CLI locally together with their IDE of choice. However, organizational security rules vary from organization to organization and some may not be able to install applications without a review from their security team. The script editor allows you to utilize just about all features of k6 right within the web app.
```

2020-11-21 05:31 UTC, ppcano commented on src/data/markdown/docs/01 guides/03 Test authoring/01 test builder.md
> +- Instructing with the [k6 API](/javascript-api).
https://github.com/loadimpact/k6-docs/pull/153/commits/786e8a91870c91073b40cc6500db279eddefd30b

2020-11-21 05:34 UTC, merged